2017-07-07 09:46:08  WARN [nioEventLoopGroup-2-1] [io.netty.channel.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.logging.InternalLoggerFactory] - Using SLF4J as the default logging framework
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.MultithreadEventLoopGroup] - -Dio.netty.eventLoopThreads: 16
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.nio.NioEventLoop] - -Dio.netty.noKeySetOptimization: false
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.nio.NioEventLoop] - -Dio.netty.selectorAutoRebuildThreshold: 512
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.DefaultChannelId] - -Dio.netty.machineId: ac:bc:32:c1:27:25:00:00 (auto-detected)
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.DefaultChannelId] - -Dio.netty.processId: 7859 (auto-detected)
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.ThreadLocalRandom] - -Dio.netty.initialSeedUniquifier: 0x0bb541821362328e
2017-07-07 10:13:09 DEBUG [main] [io.netty.channel.ChannelOutboundBuffer] - -Dio.netty.threadLocalDirectBufferSize: 65536
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - UID: 501
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - Java version: 8
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noUnsafe: false
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.ByteBuffer.cleaner: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.Buffer.address: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - sun.misc.Unsafe.theUnsafe: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - sun.misc.Unsafe.copyMemory: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.Bits.unaligned: true
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - sun.misc.Unsafe: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noJavassist: false
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - Javassist: available
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noPreferDirect: false
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.NetUtil] - Loopback interface: lo0
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.NetUtil] - Loopback address: /fe80:0:0:0:0:0:0:1%lo0 (primary)
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.NetUtil] - Loopback address: /0:0:0:0:0:0:0:1
2017-07-07 10:13:09 DEBUG [main] [io.netty.util.NetUtil] - Loopback address: /127.0.0.1
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.logging.InternalLoggerFactory] - Using SLF4J as the default logging framework
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.MultithreadEventLoopGroup] - -Dio.netty.eventLoopThreads: 16
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.nio.NioEventLoop] - -Dio.netty.noKeySetOptimization: false
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.nio.NioEventLoop] - -Dio.netty.selectorAutoRebuildThreshold: 512
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.DefaultChannelId] - -Dio.netty.machineId: ac:bc:32:c1:27:25:00:00 (auto-detected)
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.DefaultChannelId] - -Dio.netty.processId: 7864 (auto-detected)
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.ThreadLocalRandom] - -Dio.netty.initialSeedUniquifier: 0xc6690b2b602f2835
2017-07-07 10:14:01 DEBUG [main] [io.netty.channel.ChannelOutboundBuffer] - -Dio.netty.threadLocalDirectBufferSize: 65536
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent] - UID: 501
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent] - Java version: 8
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noUnsafe: false
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.ByteBuffer.cleaner: available
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.Buffer.address: available
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - sun.misc.Unsafe.theUnsafe: available
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - sun.misc.Unsafe.copyMemory: available
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent0] - java.nio.Bits.unaligned: true
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent] - sun.misc.Unsafe: available
2017-07-07 10:14:01 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noJavassist: false
2017-07-07 10:14:02 DEBUG [main] [io.netty.util.internal.PlatformDependent] - Javassist: available
2017-07-07 10:14:02 DEBUG [main] [io.netty.util.internal.PlatformDependent] - -Dio.netty.noPreferDirect: false
2017-07-07 10:14:02 DEBUG [nioEventLoopGroup-2-1] [io.netty.util.internal.JavassistTypeParameterMatcherGenerator] - Generated: io.netty.util.internal.__matchers__.com.change.hippo.netty.protocol.netty.struct.NettyMessageMatcher
2017-07-07 10:14:02 DEBUG [nioEventLoopGroup-2-1] [io.netty.util.ResourceLeakDetector] - -Dio.netty.leakDetectionLevel: simple
2017-07-07 10:14:02 DEBUG [nioEventLoopGroup-3-1] [io.netty.util.internal.JavassistTypeParameterMatcherGenerator] - Generated: io.netty.util.internal.__matchers__.com.change.hippo.netty.protocol.netty.struct.NettyMessageMatcher
2017-07-07 10:14:52  WARN [nioEventLoopGroup-3-1] [io.netty.channel.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException
2017-07-07 10:15:20  WARN [nioEventLoopGroup-2-1] [io.netty.channel.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException
